### PR TITLE
Allow to set per-signature parameters and align with rnp PR #781

### PR DESCRIPTION
**Pull request by ni4**
This PR fixes ruby tests to align with riboseinc/rnp#781 
Also it updates sign.rb to allow to set per-signature parameters.

### CODE REVIEW

**Comment by ni4** [comment]
@dewyatt What would be the correct integration process in this case? Should some version checks be done against rnp?

**Comment by ronaldtse** [comment]
@ni4 I agree that a version check would make sense here. @dewyatt ?

**Comment by dewyatt** [comment]
> @dewyatt What would be the correct integration process in this case? Should some version checks be done against rnp?

Good question, it seems like librnp's version API isn't useful for git master/non-release builds (these are built as version 0.0.0). Maybe we ought to add an `rnp_version_commit_date` API to fill in the gap? Maybe something else? What do you guys think?

**Comment by ronaldtse** [comment]
Don't we already have an alternative to 0.0.0, which is the latest version + a git commit short hash? 
With non-master releases I'm not sure if versioning is useful, unless we're speaking of some ancestor checking (that can be done with a full clone history)

**Comment by dewyatt** [comment]
> Don't we already have an alternative to 0.0.0, which is the latest version + a git commit short hash?

That is what I have set up for RPM postreleases, but these come from the `release/0.x` branch which has some versioning, not the `master` branch which is always 0.0.0.

> With non-master releases I'm not sure if versioning is useful, unless we're speaking of some ancestor checking (that can be done with a full clone history)

In the context of this PR, what would your suggestion be?

**Comment by ronaldtse** [comment]
@dewyatt I can't think of a solution 😭

**Comment by dewyatt** [comment]
@ni4 
> @dewyatt I agree that we should have some versioning thing/ Probably better would be to have some auto-incrementing build number in some small include, it would be easier to check. We could put the date there as well. We can increment those things manually, before the PR, but much handier would be to have some automatic GitHub hook. Is that possible?

I was thinking of just adding a "newest commit unix timestamp", which isn't far off from an auto-incrementing number. The release version would take priority in version checking, but for master builds the timestamp could be used. So it would be something like (kinda pseudo-code):

```c
if (rnp_version() >= rnp_version_for(0.11.1) || rnp_version_commit_timestamp() >= 1546953168) {
  // we can run our XYZ tests
}
```

I was actually playing around with this yesterday and created a `RNP_VERSION_COMMIT_TIMESTAMP` (just the timestamp of the most recent commit). It becomes a little more complicated if commits are cherry-picked out of order in the releases branch I guess, but that's probably easily resolved.

Anyways, I think it's worth some more thought.

**Comment by dewyatt** [comment]
@ni4 Does that approach seem reasonable to you too? I'm wary of the client-side git hook approach since we would always have to remember to enable the hook, etc.

**Comment by ronaldtse** [comment]
Client hooks are so hard to manage. Still remember our foray with the git hook :wink:

**Comment by ni4** [comment]
@dewyatt Sorry for a late reply. Yeah, timestamp is a great idea, and could be easily checked.

**Comment by dewyatt** [comment]
Ok, I have some changes I can push here for this after https://github.com/riboseinc/rnp/pull/792 is merged.

**Comment by dewyatt** [comment]
@ni4 Please review the added commits when you get a chance.

**Comment by ni4** [comment]
@dewyatt Thanks, everything looks good to me. So feel free to merge.

**Pull request merged**
