### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by dewyatt**
This is large since it was easiest to do a complete rm -rf and rewrite.

There's definitely some things I'd like to improve and some missing functionality, but I think it's ready to get some use and feedback.

### CODE REVIEW

**Comment by dewyatt** [comment]
@skalee FYI

**Comment by ronaldtse** [comment]
Thank you @dewyatt for the milestone. Merging now.

**Comment by dewyatt** [comment]
@ronaldtse Also, the new docs are available [here](https://www.rubydoc.info/github/riboseinc/ruby-rnp/master/toplevel) if you want to add a link to description or elsewhere.

**Comment by ronaldtse** [comment]
@dewyatt we'd definitely want to add them at https://github.com/riboseinc/rnpgp.com

**Pull request merged**
